### PR TITLE
Fixed README example compilation error.

### PR DESCRIPTION
**Pull request by jaytaylor**

### CODE REVIEW

**Review by kalloc — APPROVED** [review]

**Comment by kalloc** [comment]
thanks!

**Comment by jaytaylor** [comment]
Wow!  How did you pick that up so fast?

**Comment by kalloc** [comment]
@jaytaylor it isn't hard
how do you will use dkim?

**Comment by jaytaylor** [comment]
I'm using it to validate emails sent from our SMTP servers :)

Thank you @kalloc!

**Pull request merged**
